// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TravelAgency.DAL;

namespace TravelAgency.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241122090739_ETIIIIL")]
    partial class ETIIIIL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.CountriesDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Count_Services")
                        .HasColumnType("integer")
                        .HasColumnName("count_services");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Path_img")
                        .HasColumnType("text")
                        .HasColumnName("path_img");

                    b.Property<Guid?>("ServicesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServicesId");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.OrdersDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<Guid>("Id_Service")
                        .HasColumnType("uuid")
                        .HasColumnName("id_service");

                    b.Property<Guid>("Id_User")
                        .HasColumnType("uuid")
                        .HasColumnName("id_user");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<Guid?>("ServicesDbId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsersDbId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ordersDbsId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServicesDbId");

                    b.HasIndex("UsersDbId");

                    b.HasIndex("ordersDbsId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.Picture_servicesDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Id_Service")
                        .HasColumnType("uuid")
                        .HasColumnName("id_service");

                    b.Property<string>("Path_Img")
                        .HasColumnType("text")
                        .HasColumnName("path_img");

                    b.Property<Guid?>("Picture_servicesDbId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Picture_servicesDbId");

                    b.ToTable("picture_services");
                });

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.RequestsDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("Id_User")
                        .HasColumnType("uuid")
                        .HasColumnName("id_user");

                    b.Property<string>("Path_Img")
                        .HasColumnType("text")
                        .HasColumnName("path_img");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("UsersDbId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsersDbId");

                    b.ToTable("requests");
                });

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.ServicesDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<decimal>("Cleaning_Apartment_Price")
                        .HasColumnType("numeric")
                        .HasColumnName("cleaning_apartment_price");

                    b.Property<decimal>("Cleaning_Area_Price")
                        .HasColumnType("numeric")
                        .HasColumnName("cleaning_area_price");

                    b.Property<decimal>("Cleaning_Construction_Price")
                        .HasColumnType("numeric")
                        .HasColumnName("cleaning_construction_price");

                    b.Property<decimal>("Cleaning_Garden_Price")
                        .HasColumnType("numeric")
                        .HasColumnName("cleaning_garden_price");

                    b.Property<decimal>("Cleaning_Home_Price")
                        .HasColumnType("numeric")
                        .HasColumnName("cleaning_home_price");

                    b.Property<decimal>("Cleaning_Office_Price")
                        .HasColumnType("numeric")
                        .HasColumnName("cleaning_office_price");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<Guid>("Id_country")
                        .HasColumnType("uuid")
                        .HasColumnName("id_country");

                    b.Property<string>("Name_Service")
                        .HasColumnType("text")
                        .HasColumnName("name_service");

                    b.Property<string>("Path_Img")
                        .HasColumnType("text")
                        .HasColumnName("path_img");

                    b.Property<Guid?>("pictureServicesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("pictureServicesId");

                    b.ToTable("services");
                });

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.UsersDb", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Path_Img")
                        .HasColumnType("text")
                        .HasColumnName("path_img");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.CountriesDb", b =>
                {
                    b.HasOne("TravelAgency.Domain.ModelsDb.ServicesDb", "Services")
                        .WithMany("countriesDb")
                        .HasForeignKey("ServicesId");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.OrdersDb", b =>
                {
                    b.HasOne("TravelAgency.Domain.ModelsDb.ServicesDb", null)
                        .WithMany("ordersDb")
                        .HasForeignKey("ServicesDbId");

                    b.HasOne("TravelAgency.Domain.ModelsDb.UsersDb", "UsersDb")
                        .WithMany("ordersDb")
                        .HasForeignKey("UsersDbId");

                    b.HasOne("TravelAgency.Domain.ModelsDb.OrdersDb", "ordersDbs")
                        .WithMany()
                        .HasForeignKey("ordersDbsId");

                    b.Navigation("ordersDbs");

                    b.Navigation("UsersDb");
                });

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.Picture_servicesDb", b =>
                {
                    b.HasOne("TravelAgency.Domain.ModelsDb.Picture_servicesDb", null)
                        .WithMany("Picture_services")
                        .HasForeignKey("Picture_servicesDbId");
                });

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.RequestsDb", b =>
                {
                    b.HasOne("TravelAgency.Domain.ModelsDb.UsersDb", "UsersDb")
                        .WithMany("requestsDb")
                        .HasForeignKey("UsersDbId");

                    b.Navigation("UsersDb");
                });

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.ServicesDb", b =>
                {
                    b.HasOne("TravelAgency.Domain.ModelsDb.Picture_servicesDb", "pictureServices")
                        .WithMany()
                        .HasForeignKey("pictureServicesId");

                    b.Navigation("pictureServices");
                });

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.Picture_servicesDb", b =>
                {
                    b.Navigation("Picture_services");
                });

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.ServicesDb", b =>
                {
                    b.Navigation("countriesDb");

                    b.Navigation("ordersDb");
                });

            modelBuilder.Entity("TravelAgency.Domain.ModelsDb.UsersDb", b =>
                {
                    b.Navigation("ordersDb");

                    b.Navigation("requestsDb");
                });
#pragma warning restore 612, 618
        }
    }
}
